version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            
workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build
